export const DataSection = [
    {
        id : 0,
        h1 : "Hi, I'm Codehal",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'translate-x-0 ' ,
        hideSection : 'translate-x-[-100%] ',
        showStyles : "opacity-100 blur-[0]",
        hideStyles : 'opacity-0 blur-3xl',
        status : true,
    },
    {
        id : 1,
        h1 : "Keep Scrolling",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'translate-x-0! ' ,
        hideSection : 'translate-x-[100%]! ',
        showStyles : "opacity-100 blur-[0] text-[#0f0]",
        hideStyles : 'opacity-0 blur-3xl ',
        status : false,
    },
    {
        id : 2,
        h1 : "Nice ",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'scale-100 ' ,
        hideSection : 'scale-[.2]',
        showStyles : " opacity-100 blur-[0] text-[#e0f]",
        hideStyles : ' opacity-0 blur-3xl',
        status : false,
    },
    {
        id : 4,
        h1 : "Very Good ",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : '' ,
        hideSection : '',
        showStyles : "  text-[#ff0]",
        hideStyles : ' ',
        spanClass : 'absolute top-0 right-0 h-[100%] bg-[#1f242d] duration-1000 delay[.2s]',
        spanShow : "w-[0]",
        spanHide : 'w-[100%]',
        status : false,
    },
    
]