export const DataSection = [
    {
        id : 10,
        h1 : "Hi, I'm Amir",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'translate-x-0 ' ,
        hideSection : 'translate-x-[-100%] ',
        showStyles : "opacity-100 blur-[0]",
        hideStyles : 'opacity-0 blur-3xl',
        status : true,
    },
    {
        id : 11,
        h1 : "Keep Scrolling",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'translate-x-0! ' ,
        hideSection : 'translate-x-[100%]! ',
        showStyles : "opacity-100 blur-[0] text-[#0f0]",
        hideStyles : 'opacity-0 blur-3xl ',
        status : false,
    },
    {
        id : 12,
        h1 : "Nice ",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showSection : 'scale-100 ' ,
        hideSection : 'scale-[.2]',
        showStyles : " opacity-100 blur-[0] text-[#e0f]",
        hideStyles : ' opacity-0 blur-3xl',
        status : false,
    },
    {
        id :13,
        h1 : "Very Good ",
        p : "Animation on Scroll using HTML CSS and Javascript",
        showStyles : "  text-[#ff0]",
        hideStyles : 'text-[#ff0]',
        spanShow : "w-[0]",
        spanHide : 'w-[100%]',
        status : false,
    },
    {
        id : 14,
        src1 : "https://images.unsplash.com/photo-1508974239320-0a029497e820?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        src2 : "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        src3 : "https://images.unsplash.com/photo-1533416784636-2b0ccfea6b97?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        status : false,
    },
    
]